name = "KidiVerse"
license = "MIT"
licenselink = "https://github.com/ShawnSWu/hugo-kidiverse/blob/main/LICENSE"
description = "Hugo static-site theme for Obsidian-style Markdown notebooks with AI semantic graph visualization"
homepage = "https://github.com/ShawnSWu/hugo-kidiverse"
demosite = "https://shawnswu.github.io/KidiVerse/"
tags = ["responsive", "minimal", "dark", "obsidian", "knowledge-base", "wiki", "notes", "markdown", "graph", "ai"]
features = ["responsive", "dark mode", "sidebar", "obsidian-compatible", "semantic-graph", "search"]
min_version = "0.90.0"

[author]
  name = "Shawn Wu"
  homepage = "https://github.com/ShawnSWu"
