# Kidiverse demo site configuration
baseURL = "https://example.com/"  # change to your own domain when deploying
languageCode = "en-us"
title = "Kidiverse Demo Site"

# Tell Hugo to load the theme from one directory above exampleSite/
# (Kidiverse lives in the repository root)
theme = "kidiverse"
themesDir = ".."

disableKinds = ["taxonomy", "term"]  # demo site keeps output minimal

[params]
  description = "Personal knowledge garden powered by Kidiverse"
  # You can copy more advanced params from ../exampleSite/config.toml in the main repo
